spring:
  application:
    name: creator-ledger

logging:
  level:
    org.springframework.modulith: INFO
    org.creatorledger: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{correlationId:-}] --- [%t] %-40.40logger{39} : %m%n"
